project:
  type: website
  output-dir: docs

website:
  title: "personal_website"
  favicon: favicon.jpg
  navbar:
    logo: logo.jpg
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



